apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd01
spec:
  destination:
    namespace: test01
    server: https://api.rhodainsmall01.lab.upshift.rdu2.redhat.com:6443
  project: default
  source:
    path: app
    repoURL: https://github.com/siamaksade/openshift-gitops-getting-started
    targetRevision: HEAD
  syncPolicy: {}

